export const navItems = [
  { text: "Dashboard", path: "/" },
  { text: "Typography", path: "/typography" },
  { text: "Buttons", path: "/buttons" },
  { text: "Text Fields", path: "/textfields" },
  { text: "Layout", path: "/layout" },
  { text: "Card", path: "/card" },
  { text: "Accordion", path: "/accordion" },
  { text: "Nav Items", path: "/navitems" },
  { text: "List", path: "/list" },
  { text: "Chip", path: "/chip" },
  { text: "Table", path: "/table" },
  { text: "Alerts", path: "/alerts" },
  { text: "Snackbar", path: "/snackbar" },
  { text: "Dialog", path: "/dialog" },
  { text: "Progress", path: "/progress" },
  { text: "Skelton", path: "/skelton" },
  { text: "Date Time", path: "/datetimerange" },
  { text: "Tabs", path: "/tabs" },
  { text: "Timeline", path: "/timeline" },
  { text: "Masonry", path: "/masonry" },
  { text: "Theme Customization", path: "/themecustomization" },
]; 